Issue 46 relay env
iporaitech/pwr2-docker pull request #47
Opened 2016-10-05 19:37 UTC by edipox

2016-10-05 19:50 UTC, hisapy requested changes
Just those minors changes and of course some "manual testing" to make sure that the environment's store is cleared up upon logout.

2016-10-05 19:50 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +    return (<Router history={browserHistory}
Please write it like:
```javascript
return(
  <Router history="..."
    .....
  </Router>
);

2016-10-05 19:50 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +      environment={env}>
I think `environment={Auth.getEnvironment()}` would be better ... I don't know why suddenly I completely missed where `env` came from.

2016-10-06 19:35 UTC, hisapy requested changes
Looking good. Just a few touches to get this done.

2016-10-06 19:35 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +      <Router history={browserHistory} routes={routes}
What about ?
```javascript
<Router history={browserHistory}
  render={applyRouterMiddleware(useRelay)}
  environment={this.state.environment}>
  {routes}
</Router>
```

2016-10-06 19:35 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +class Application extends React.Component{
If you want to make this file a little bit more _cleaner_ then you might want to move this `class` to its own file **app.js**. 

Anyway, I don't mind having this class here.

2016-10-06 19:35 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +    <Route path="/admin" component={AdminLayout} onEnter={requireAuth} >
Can you please remove the whitespace before the `>`?

2016-10-06 20:21 UTC, edipox commented on apps/webapp/web/static/js/index.js
> +class Application extends React.Component{
For now as the code is very simple I won't move this component. But if we get more and more routes and the Application component gets more complex, maybe we could separate the route logic in a Router and the Application component in another file.

In that case the Router could look something like this:
```javascript
class Filter {

  static requireAuth(nextState, replace) {
    if (!Auth.loggedIn()) {
      replace({
        pathname: "/login",
        state: {
          nextPathname: nextState.location.pathname
        }
      })
    }
  }

  static verifySession(nextState, replace) {
    if (Auth.loggedIn()) 
      replace({pathname: "/admin"})
  }
}

export default  (
  <Route path="/">
    <IndexRoute component={Hello}/>
    <Route path="/login" component={Login} onEnter={Filter.verifySession}/>
    <Route path="/admin" component={AdminLayout} onEnter={Filter.requireAuth}>
      <IndexRoute component={Hello}/>
      <Route path="star-wars" component={StarWarsApp} queries={StarWarsQueries}/>
      <Route path="graphiql" component={GraphiQL}/>
    </Route>
  </Route>
)
```

2016-10-06 21:09 UTC, hisapy commented on apps/webapp/web/static/js/index.js
> +class Application extends React.Component{
👍

2016-10-06 21:12 UTC, hisapy approved these changes
Looks nice and ready to go

2016-10-06 23:28 UTC, closed without merging