Feature/59 Users CRUD
iporaitech/pwr2-docker pull request #62
Opened 2017-01-03 20:00 UTC by rsjavier14

2017-01-03 22:55 UTC, hisapy reviewed
For now I have these comments/questions. Please take care of them and let's see if I can find more stuff later.

2017-01-03 22:55 UTC, hisapy commented on .gitignore
> +ui/node_modules
Please remove specific **apps** stuff from the global .gitignore and add them to each specific app's .gitignore. For example, there is already a .gitignore inside _apps/webapp_

2017-01-03 22:55 UTC, hisapy commented on apps/core/graphql/schema.ex
> +  import_types Core.GraphQL.Users.Types
Please make this `Core.GraphQL.Types.User` to be consistent with all the `Core.GraphQL` stuff.

2017-01-03 22:55 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +    @desc "El Jurista users"
This project is not El Jurista. Please update this ASAP

2017-01-03 22:55 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +      resolve fn
Please add *authorization* logic here. Only `admin` or `superadmin` `viewer` should be allowed to list users.

2017-01-03 22:55 UTC, hisapy commented on apps/core/graphql/users/types.ex
> +defmodule Core.GraphQL.Users.Types do
Please change this name according to one of the previous comments

2017-01-03 22:55 UTC, hisapy commented on apps/webapp/web/controllers/admin/page_controller.ex
> +  def users(conn, _params) do
I think we actually don't need this Admin.PageController anymore.

2017-01-03 22:55 UTC, hisapy commented on mix.lock
> +%{"absinthe": {:hex, :absinthe, "1.2.1", "67099c701aca32c8f5cc8a0147d578eaecccf1bcb460edc746d467ccc7881ed8", [:mix], []},
Why is this file updated ? ...

2017-01-03 22:55 UTC, hisapy commented on ui/core/src/AppLayout.js
> -import { mdlUpgrade } from 'react-to-mdl';
Why is this removed?

2017-01-03 23:36 UTC, rsjavier14 commented on apps/webapp/web/controllers/admin/page_controller.ex
> +  def users(conn, _params) do
Is it true, can I delete it or leave it?

2017-01-03 23:36 UTC, rsjavier14 commented on mix.lock
> +%{"absinthe": {:hex, :absinthe, "1.2.1", "67099c701aca32c8f5cc8a0147d578eaecccf1bcb460edc746d467ccc7881ed8", [:mix], []},
When installing dependencies with `mix deps.get` the file was modified.

2017-01-03 23:37 UTC, rsjavier14 commented on ui/core/src/AppLayout.js
> -import { mdlUpgrade } from 'react-to-mdl';
I think it's not being used

2017-01-04 18:37 UTC, hisapy commented on apps/webapp/web/controllers/admin/page_controller.ex
> +  def users(conn, _params) do
Please delete it.

2017-01-04 18:38 UTC, hisapy commented on ui/core/src/AppLayout.js
> -import { mdlUpgrade } from 'react-to-mdl';
ok

2017-01-04 20:18 UTC, hisapy requested changes
Some stuff to DRY and some stuff to fix.

2017-01-04 20:18 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +            Map.delete(query_params, :search)
Let's replace this 2 `Map.delete` with:
 ```elixir
pagination_args = Map.take(query_params, [:first, :after, :last, :before])
``` 
... if atom keys don't work you can try with string keys

2017-01-04 20:18 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +          full_query = fn query ->
This is not necessary.

2017-01-04 20:18 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +          with true <- authorized,
`with` is generally used when you have multiple conditions that should all be met simultaneously and you only have the `authorized` condition here. Also, in line 49, I don't see the needed `<-` you suppose evaluate before `do`. 

Please change this to:

```elixir
if authorized do
  conn = 
     from u in User, order_by: [{^order, u.inserted_at}]
     |> Connection.from_query(&Repo.all/1, pagination_args)
else
  Core.GraphQL.Resolver.unauthorized_error
end
```

Of course, any other `:error` perhaps will be treated as a `500`

2017-01-04 20:18 UTC, hisapy commented on apps/core/lib/core/models/user.ex
> +    field :password_confirmation, :string, virtual: true
You don't need this virtual field according to the docs of [validate_confirmation/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_confirmation/3)

2017-01-04 20:18 UTC, hisapy commented on apps/webapp/.gitignore
> +priv/static/js/*.chunk.js*
Can you please put comments above what's being ignored? ... For example, I believe that by using `.js*` we're ignoring some stuff like `some_file.js.map`, aren't we?.

Also please remove names we're not referencing anymore. For example **app** and **vendor** perhaps

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/RelayQueryConfig.js
> +const NodeQueries = {
Please move both of this queries **shared** dir. Both `viewer` and `node` are going to be used in many modules

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/Form.js
> +                options={[
Ideally, we should provide values like this from a graphql. Please add a TODO so we don't forget to fix/improve this in the future

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/Form.js
> +    console.log(this.state.user);
Please remove this `console.log`

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/Form.js
> +          // TODO: get rid of reload and use router.
Is this just hiding the loading?, not going to users list after commit update?

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/Edit.js
> +// file: users/Edit.js
You can use the same user form to edit a user. Please DRY this. Remember, React encourages the _use_ of reusable components.

2017-01-04 20:18 UTC, hisapy commented on ui/core/src/users/AddUserMutation.js
> +// file: src/users/AdduserMutation.js
This and EditUserMutation looks almost exactly the same. Please DRY.

2017-01-09 18:48 UTC, hisapy requested changes

2017-01-09 18:48 UTC, hisapy commented on .env.example
> +PWR2MAILER_SERVER="localhost"
typo here

2017-01-09 18:48 UTC, hisapy commented on apps/core/graphql/schema.ex
> +  import_types Core.GraphQL.Types.User
Please move this to line 8

2017-01-18 11:45 UTC, hisapy requested changes
There are pending changes from the last review and a few others from this one. Please check them one by one so you don't miss any.

2017-01-18 11:45 UTC, hisapy commented on .env.example
> +## SET ENV VARS TO BE USED IN THIS PROJECT
Just for the record, the **.env** file will allow us to use this project with our without **Docker** almost seamlessly

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/schema.ex
> +  import_types Core.GraphQL.Types.User
@rsjavier14 please do as I said in the comment above

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/types/user.ex
> +            function = fn args ->
Please rename this variable with a more meaningful name, perhaps something like `insert_user` will be a lot more descriptive.

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/types/user.ex
> +        field :id, non_null(:id)
What `id` should  you provide when **adding a User** ?

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/types/user.ex
> +          with true <- authorized,
The `with` clause is not meant to be used this way. You're providing only one success condition but you have 3 different fail causes. Please change this logic to use a more appropriate construct. 

For more info see the [`with` documentation](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#with/1)

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/types/user.ex
> +                errors: Enum.map(errors, fn (err) ->
Actually, there is a `ErrorHelpers.translate_error` we can use to _render_ errors correctly

2017-01-18 11:45 UTC, hisapy commented on apps/core/graphql/types/viewer.ex
> +              %{errors: %{message: "ERROR 500. Server internal error"}}
ERROR 500 is generated when an exception raises from the code. It is not something you manually send to the client. **401** is the error code typically used for **Unauthorized** requests. Please change this accordingly

2017-01-18 11:45 UTC, hisapy commented on apps/core/lib/core/models/user.ex
> +  def update_changeset(model, params) do
You don't need an `update_changeset` to update the User registration. You can use the `registration_changeset` for this. Moreover, there is a lot of duplicated code from the latter in this changeset.

2017-01-18 11:45 UTC, hisapy commented on ui/core/src/users/List.js
> +                <DataTableTH nonNumeric={true}> Usuario </DataTableTH>
Please use english for this kind of _labels_ or _headers_ here an throughout this project

2017-01-18 11:45 UTC, hisapy commented on ui/core/src/users/RelayQueryConfig.js
> +const NodeQueries = {
This should not be here anymore @rsjavier14, since you've moved them to **shared** dir

2017-01-18 11:45 UTC, hisapy commented on ui/core/src/users/index.js
> +    title: 'Lista de Usuarios',
Again, please change to english

2017-01-18 14:32 UTC, rsjavier14 commented on apps/core/graphql/types/user.ex
> +        field :id, non_null(:id)
**id** is not required to add user. I am using the `id` to be able to create or edit a user. Now, as you can see `id` is not null, however at the time of creating the user is added normally and does not arise any type of error.

2017-01-18 14:35 UTC, rsjavier14 commented on apps/core/lib/core/models/user.ex
> +  def update_changeset(model, params) do
I think I should do it somehow, because in the case of adding a user the password is required, but to update the user is optional.

2017-01-18 14:37 UTC, rsjavier14 commented on apps/core/graphql/types/user.ex
> +                errors: Enum.map(errors, fn (err) ->
Now I am seeing the documentation to make the change here

2017-01-18 17:05 UTC, rsjavier14 commented on apps/core/graphql/types/user.ex
> +                errors: Enum.map(errors, fn (err) ->
Now I am seeing the documentation to make the change here

2017-01-18 17:32 UTC, hisapy commented on apps/core/lib/core/models/user.ex
> +  def update_changeset(model, params) do
The to DRY it up you can create a `password_changeset`.

2017-01-18 17:34 UTC, hisapy commented on apps/core/graphql/types/user.ex
> +        field :id, non_null(:id)
After we merge this pull request we're going to confirm the behavior of this and report a bug to Absinthe if necessary.

2017-01-18 18:03 UTC, rsjavier14 commented on apps/core/lib/core/models/user.ex
> +  def update_changeset(model, params) do
`password_changeset`? I don't understand

2017-01-18 18:21 UTC, hisapy commented on apps/core/lib/core/models/user.ex
> +  def update_changeset(model, params) do
If you don't want to manage the password in the `registration_changeset` then just extract it to its own changeset.

2017-01-23 19:58 UTC, hisapy requested changes
A few changes left

2017-01-23 19:58 UTC, hisapy commented on apps/core/lib/core/models/user.ex
> +  def required_password_changeset(model, params) do
`validate_confirmation` should be in this changeset, and this changeset, as we discussed previously, should be called `password_changeset`

2017-01-23 19:58 UTC, hisapy commented on apps/webapp/web/views/layout_view.ex
> +        base_url = "http://localhost:#{System.get_env("PWR2_HTTP_PORT")}"
Please remove this `base_url` variable if not used.

2017-01-23 19:58 UTC, hisapy commented on ui/core/src/users/AddUserMutation.js
> +// file: src/users/UserMutation.js
Please remove this comment or update it to the actual filename.

2017-01-23 19:58 UTC, hisapy commented on ui/core/src/users/EditUserMutation.js
> +// file: src/users/UserMutation.js
Please remove this comment or update it to its actual filename

2017-01-24 11:51 UTC, hisapy approved these changes

2017-01-24 11:53 UTC, merged